version: "3"
services:
    app:
        build: .
        depends_on:
            - db_host
        ports:
            - "80:80"
        links:
            - db_host
    db_host:
        image: mongo:latest
        ports:
            - "80:80"
        environment:
            - MONGO_INITDB_DATABASE=movies
